
package smapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "customFaultDetail", targetNamespace = "http://www.sonos.com/Services/1.1")
public class CustomFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CustomFaultDetail faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CustomFault(String message, CustomFaultDetail faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CustomFault(String message, CustomFaultDetail faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: smapi.CustomFaultDetail
     */
    public CustomFaultDetail getFaultInfo() {
        return faultInfo;
    }

}
