
package smapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SonosSoap", targetNamespace = "http://www.sonos.com/Services/1.1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SonosSoap {


    /**
     * 
     * @param password
     * @param credentials
     * @param context
     * @param username
     * @return
     *     returns java.lang.String
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#getSessionId")
    @WebResult(name = "getSessionIdResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "getSessionId", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetSessionId")
    @ResponseWrapper(localName = "getSessionIdResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetSessionIdResponse")
    public String getSessionId(
        @WebParam(name = "username", targetNamespace = "http://www.sonos.com/Services/1.1")
        String username,
        @WebParam(name = "password", targetNamespace = "http://www.sonos.com/Services/1.1")
        String password,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param count
     * @param context
     * @param index
     * @param id
     * @param recursive
     * @return
     *     returns smapi.MediaList
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#getMetadata")
    @WebResult(name = "getMetadataResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "getMetadata", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetMetadata")
    @ResponseWrapper(localName = "getMetadataResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetMetadataResponse")
    public MediaList getMetadata(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "index", targetNamespace = "http://www.sonos.com/Services/1.1")
        int index,
        @WebParam(name = "count", targetNamespace = "http://www.sonos.com/Services/1.1")
        int count,
        @WebParam(name = "recursive", targetNamespace = "http://www.sonos.com/Services/1.1")
        Boolean recursive,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param context
     * @param id
     * @return
     *     returns smapi.ExtendedMetadata
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#getExtendedMetadata")
    @WebResult(name = "getExtendedMetadataResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "getExtendedMetadata", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetExtendedMetadata")
    @ResponseWrapper(localName = "getExtendedMetadataResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetExtendedMetadataResponse")
    public ExtendedMetadata getExtendedMetadata(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param context
     * @param id
     * @param type
     * @return
     *     returns java.lang.String
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#getExtendedMetadataText")
    @WebResult(name = "getExtendedMetadataTextResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "getExtendedMetadataText", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetExtendedMetadataText")
    @ResponseWrapper(localName = "getExtendedMetadataTextResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetExtendedMetadataTextResponse")
    public String getExtendedMetadataText(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "type", targetNamespace = "http://www.sonos.com/Services/1.1")
        String type,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param context
     * @return
     *     returns smapi.UserInfo
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#getUserInfo")
    @WebResult(name = "getUserInfoResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "getUserInfo", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetUserInfo")
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetUserInfoResponse")
    public UserInfo getUserInfo(
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param rating
     * @param context
     * @param id
     * @return
     *     returns smapi.ItemRating
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#rateItem")
    @WebResult(name = "rateItemResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "rateItem", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.RateItem")
    @ResponseWrapper(localName = "rateItemResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.RateItemResponse")
    public ItemRating rateItem(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "rating", targetNamespace = "http://www.sonos.com/Services/1.1")
        int rating,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param count
     * @param context
     * @param index
     * @param term
     * @param id
     * @return
     *     returns smapi.MediaList
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#search")
    @WebResult(name = "searchResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "search", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.SearchResponse")
    public MediaList search(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "term", targetNamespace = "http://www.sonos.com/Services/1.1")
        String term,
        @WebParam(name = "index", targetNamespace = "http://www.sonos.com/Services/1.1")
        int index,
        @WebParam(name = "count", targetNamespace = "http://www.sonos.com/Services/1.1")
        int count,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param context
     * @param id
     * @return
     *     returns smapi.MediaMetadata
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#getMediaMetadata")
    @WebResult(name = "getMediaMetadataResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "getMediaMetadata", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetMediaMetadata")
    @ResponseWrapper(localName = "getMediaMetadataResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetMediaMetadataResponse")
    public MediaMetadata getMediaMetadata(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param deviceSessionToken
     * @param contentKey
     * @param credentials
     * @param secondsSinceExplicit
     * @param getMediaURIResult
     * @param httpHeaders
     * @param deviceSessionKey
     * @param positionInformation
     * @param privateDataFieldName
     * @param uriTimeout
     * @param context
     * @param action
     * @param id
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#getMediaURI")
    @RequestWrapper(localName = "getMediaURI", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetMediaURI")
    @ResponseWrapper(localName = "getMediaURIResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetMediaURIResponse")
    public void getMediaURI(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "action", targetNamespace = "http://www.sonos.com/Services/1.1")
        MediaUriAction action,
        @WebParam(name = "secondsSinceExplicit", targetNamespace = "http://www.sonos.com/Services/1.1")
        Integer secondsSinceExplicit,
        @WebParam(name = "deviceSessionToken", targetNamespace = "http://www.sonos.com/Services/1.1", mode = WebParam.Mode.INOUT)
        Holder<String> deviceSessionToken,
        @WebParam(name = "getMediaURIResult", targetNamespace = "http://www.sonos.com/Services/1.1", mode = WebParam.Mode.OUT)
        Holder<String> getMediaURIResult,
        @WebParam(name = "deviceSessionKey", targetNamespace = "http://www.sonos.com/Services/1.1", mode = WebParam.Mode.OUT)
        Holder<EncryptionContext> deviceSessionKey,
        @WebParam(name = "contentKey", targetNamespace = "http://www.sonos.com/Services/1.1", mode = WebParam.Mode.OUT)
        Holder<EncryptionContext> contentKey,
        @WebParam(name = "httpHeaders", targetNamespace = "http://www.sonos.com/Services/1.1", mode = WebParam.Mode.OUT)
        Holder<HttpHeaders> httpHeaders,
        @WebParam(name = "uriTimeout", targetNamespace = "http://www.sonos.com/Services/1.1", mode = WebParam.Mode.OUT)
        Holder<Integer> uriTimeout,
        @WebParam(name = "positionInformation", targetNamespace = "http://www.sonos.com/Services/1.1", mode = WebParam.Mode.OUT)
        Holder<PositionInformation> positionInformation,
        @WebParam(name = "privateDataFieldName", targetNamespace = "http://www.sonos.com/Services/1.1", mode = WebParam.Mode.OUT)
        Holder<String> privateDataFieldName,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param context
     * @param id
     * @return
     *     returns java.lang.String
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#getScrollIndices")
    @WebResult(name = "getScrollIndicesResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "getScrollIndices", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetScrollIndices")
    @ResponseWrapper(localName = "getScrollIndicesResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetScrollIndicesResponse")
    public String getScrollIndices(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param context
     * @param favorite
     * @return
     *     returns java.lang.String
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#createItem")
    @WebResult(name = "createItemResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "createItem", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.CreateItem")
    @ResponseWrapper(localName = "createItemResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.CreateItemResponse")
    public String createItem(
        @WebParam(name = "favorite", targetNamespace = "http://www.sonos.com/Services/1.1")
        String favorite,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param context
     * @param favorite
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#deleteItem")
    @RequestWrapper(localName = "deleteItem", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.DeleteItem")
    @ResponseWrapper(localName = "deleteItemResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.DeleteItemResponse")
    public void deleteItem(
        @WebParam(name = "favorite", targetNamespace = "http://www.sonos.com/Services/1.1")
        String favorite,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param context
     * @return
     *     returns smapi.LastUpdate
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#getLastUpdate")
    @WebResult(name = "getLastUpdateResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "getLastUpdate", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetLastUpdate")
    @ResponseWrapper(localName = "getLastUpdateResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetLastUpdateResponse")
    public LastUpdate getLastUpdate(
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param context
     * @param errorCode
     * @param id
     * @param message
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#reportStatus")
    @RequestWrapper(localName = "reportStatus", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.ReportStatus")
    @ResponseWrapper(localName = "reportStatusResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.ReportStatusResponse")
    public void reportStatus(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "errorCode", targetNamespace = "http://www.sonos.com/Services/1.1")
        int errorCode,
        @WebParam(name = "message", targetNamespace = "http://www.sonos.com/Services/1.1")
        String message,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param privateData
     * @param seconds
     * @param credentials
     * @param offsetMillis
     * @param context
     * @param contextId
     * @param id
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#setPlayedSeconds")
    @RequestWrapper(localName = "setPlayedSeconds", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.SetPlayedSeconds")
    @ResponseWrapper(localName = "setPlayedSecondsResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.SetPlayedSecondsResponse")
    public void setPlayedSeconds(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "seconds", targetNamespace = "http://www.sonos.com/Services/1.1")
        int seconds,
        @WebParam(name = "contextId", targetNamespace = "http://www.sonos.com/Services/1.1")
        String contextId,
        @WebParam(name = "privateData", targetNamespace = "http://www.sonos.com/Services/1.1")
        String privateData,
        @WebParam(name = "offsetMillis", targetNamespace = "http://www.sonos.com/Services/1.1")
        Integer offsetMillis,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param privateData
     * @param seconds
     * @param credentials
     * @param offsetMillis
     * @param context
     * @param contextId
     * @param id
     * @return
     *     returns smapi.ReportPlaySecondsResult
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#reportPlaySeconds")
    @WebResult(name = "reportPlaySecondsResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "reportPlaySeconds", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.ReportPlaySeconds")
    @ResponseWrapper(localName = "reportPlaySecondsResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.ReportPlaySecondsResponse")
    public ReportPlaySecondsResult reportPlaySeconds(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "seconds", targetNamespace = "http://www.sonos.com/Services/1.1")
        int seconds,
        @WebParam(name = "contextId", targetNamespace = "http://www.sonos.com/Services/1.1")
        String contextId,
        @WebParam(name = "privateData", targetNamespace = "http://www.sonos.com/Services/1.1")
        String privateData,
        @WebParam(name = "offsetMillis", targetNamespace = "http://www.sonos.com/Services/1.1")
        Integer offsetMillis,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param offsetMillis
     * @param context
     * @param contextId
     * @param id
     * @param status
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#reportPlayStatus")
    @RequestWrapper(localName = "reportPlayStatus", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.ReportPlayStatus")
    @ResponseWrapper(localName = "reportPlayStatusResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.ReportPlayStatusResponse")
    public void reportPlayStatus(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "status", targetNamespace = "http://www.sonos.com/Services/1.1")
        String status,
        @WebParam(name = "contextId", targetNamespace = "http://www.sonos.com/Services/1.1")
        String contextId,
        @WebParam(name = "offsetMillis", targetNamespace = "http://www.sonos.com/Services/1.1")
        Integer offsetMillis,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param context
     * @param type
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#reportAccountAction")
    @RequestWrapper(localName = "reportAccountAction", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.ReportAccountAction")
    @ResponseWrapper(localName = "reportAccountActionResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.ReportAccountActionResponse")
    public void reportAccountAction(
        @WebParam(name = "type", targetNamespace = "http://www.sonos.com/Services/1.1")
        String type,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param householdId
     * @param osVersion
     * @param callbackPath
     * @param credentials
     * @param context
     * @param sonosAppName
     * @param hardware
     * @return
     *     returns smapi.AppLinkResult
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#getAppLink")
    @WebResult(name = "getAppLinkResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "getAppLink", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetAppLink")
    @ResponseWrapper(localName = "getAppLinkResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetAppLinkResponse")
    public AppLinkResult getAppLink(
        @WebParam(name = "householdId", targetNamespace = "http://www.sonos.com/Services/1.1")
        String householdId,
        @WebParam(name = "hardware", targetNamespace = "http://www.sonos.com/Services/1.1")
        String hardware,
        @WebParam(name = "osVersion", targetNamespace = "http://www.sonos.com/Services/1.1")
        String osVersion,
        @WebParam(name = "sonosAppName", targetNamespace = "http://www.sonos.com/Services/1.1")
        String sonosAppName,
        @WebParam(name = "callbackPath", targetNamespace = "http://www.sonos.com/Services/1.1")
        String callbackPath,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param householdId
     * @param credentials
     * @param context
     * @return
     *     returns smapi.DeviceLinkCodeResult
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#getDeviceLinkCode")
    @WebResult(name = "getDeviceLinkCodeResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "getDeviceLinkCode", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetDeviceLinkCode")
    @ResponseWrapper(localName = "getDeviceLinkCodeResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetDeviceLinkCodeResponse")
    public DeviceLinkCodeResult getDeviceLinkCode(
        @WebParam(name = "householdId", targetNamespace = "http://www.sonos.com/Services/1.1")
        String householdId,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param householdId
     * @param linkCode
     * @param linkDeviceId
     * @param callbackPath
     * @param credentials
     * @param context
     * @return
     *     returns smapi.DeviceAuthTokenResult
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#getDeviceAuthToken")
    @WebResult(name = "getDeviceAuthTokenResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "getDeviceAuthToken", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetDeviceAuthToken")
    @ResponseWrapper(localName = "getDeviceAuthTokenResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetDeviceAuthTokenResponse")
    public DeviceAuthTokenResult getDeviceAuthToken(
        @WebParam(name = "householdId", targetNamespace = "http://www.sonos.com/Services/1.1")
        String householdId,
        @WebParam(name = "linkCode", targetNamespace = "http://www.sonos.com/Services/1.1")
        String linkCode,
        @WebParam(name = "linkDeviceId", targetNamespace = "http://www.sonos.com/Services/1.1")
        String linkDeviceId,
        @WebParam(name = "callbackPath", targetNamespace = "http://www.sonos.com/Services/1.1")
        String callbackPath,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param context
     * @return
     *     returns smapi.DeviceAuthTokenResult
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#refreshAuthToken")
    @WebResult(name = "refreshAuthTokenResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "refreshAuthToken", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.RefreshAuthToken")
    @ResponseWrapper(localName = "refreshAuthTokenResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.RefreshAuthTokenResponse")
    public DeviceAuthTokenResult refreshAuthToken(
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param duration
     * @param credentials
     * @param context
     * @param startTime
     * @param id
     * @return
     *     returns smapi.SegmentMetadataList
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#getStreamingMetadata")
    @WebResult(name = "getStreamingMetadataResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "getStreamingMetadata", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetStreamingMetadata")
    @ResponseWrapper(localName = "getStreamingMetadataResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetStreamingMetadataResponse")
    public SegmentMetadataList getStreamingMetadata(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "startTime", targetNamespace = "http://www.sonos.com/Services/1.1")
        XMLGregorianCalendar startTime,
        @WebParam(name = "duration", targetNamespace = "http://www.sonos.com/Services/1.1")
        int duration,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param deviceSessionToken
     * @param credentials
     * @param context
     * @param id
     * @param uri
     * @return
     *     returns smapi.ContentKey
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#getContentKey")
    @WebResult(name = "contentKey", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "getContentKey", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetContentKey")
    @ResponseWrapper(localName = "getContentKeyResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.GetContentKeyResponse")
    public ContentKey getContentKey(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "uri", targetNamespace = "http://www.sonos.com/Services/1.1")
        String uri,
        @WebParam(name = "deviceSessionToken", targetNamespace = "http://www.sonos.com/Services/1.1")
        String deviceSessionToken,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param containerType
     * @param seedId
     * @param context
     * @param title
     * @param parentId
     * @return
     *     returns smapi.CreateContainerResult
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#createContainer")
    @WebResult(name = "createContainerResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "createContainer", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.CreateContainer")
    @ResponseWrapper(localName = "createContainerResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.CreateContainerResponse")
    public CreateContainerResult createContainer(
        @WebParam(name = "containerType", targetNamespace = "http://www.sonos.com/Services/1.1")
        String containerType,
        @WebParam(name = "title", targetNamespace = "http://www.sonos.com/Services/1.1")
        String title,
        @WebParam(name = "parentId", targetNamespace = "http://www.sonos.com/Services/1.1")
        String parentId,
        @WebParam(name = "seedId", targetNamespace = "http://www.sonos.com/Services/1.1")
        String seedId,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param updateId
     * @param credentials
     * @param context
     * @param index
     * @param id
     * @param parentId
     * @return
     *     returns smapi.AddToContainerResult
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#addToContainer")
    @WebResult(name = "addToContainerResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "addToContainer", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.AddToContainer")
    @ResponseWrapper(localName = "addToContainerResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.AddToContainerResponse")
    public AddToContainerResult addToContainer(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "parentId", targetNamespace = "http://www.sonos.com/Services/1.1")
        String parentId,
        @WebParam(name = "index", targetNamespace = "http://www.sonos.com/Services/1.1")
        int index,
        @WebParam(name = "updateId", targetNamespace = "http://www.sonos.com/Services/1.1")
        String updateId,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param context
     * @param id
     * @param title
     * @return
     *     returns smapi.RenameContainerResult
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#renameContainer")
    @WebResult(name = "renameContainerResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "renameContainer", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.RenameContainer")
    @ResponseWrapper(localName = "renameContainerResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.RenameContainerResponse")
    public RenameContainerResult renameContainer(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "title", targetNamespace = "http://www.sonos.com/Services/1.1")
        String title,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param credentials
     * @param context
     * @param id
     * @return
     *     returns smapi.DeleteContainerResult
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#deleteContainer")
    @WebResult(name = "deleteContainerResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "deleteContainer", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.DeleteContainer")
    @ResponseWrapper(localName = "deleteContainerResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.DeleteContainerResponse")
    public DeleteContainerResult deleteContainer(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param updateId
     * @param indices
     * @param credentials
     * @param context
     * @param id
     * @return
     *     returns smapi.RemoveFromContainerResult
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#removeFromContainer")
    @WebResult(name = "removeFromContainerResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "removeFromContainer", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.RemoveFromContainer")
    @ResponseWrapper(localName = "removeFromContainerResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.RemoveFromContainerResponse")
    public RemoveFromContainerResult removeFromContainer(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "indices", targetNamespace = "http://www.sonos.com/Services/1.1")
        String indices,
        @WebParam(name = "updateId", targetNamespace = "http://www.sonos.com/Services/1.1")
        String updateId,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

    /**
     * 
     * @param updateId
     * @param credentials
     * @param context
     * @param from
     * @param id
     * @param to
     * @return
     *     returns smapi.ReorderContainerResult
     * @throws CustomFault
     */
    @WebMethod(action = "http://www.sonos.com/Services/1.1#reorderContainer")
    @WebResult(name = "reorderContainerResult", targetNamespace = "http://www.sonos.com/Services/1.1")
    @RequestWrapper(localName = "reorderContainer", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.ReorderContainer")
    @ResponseWrapper(localName = "reorderContainerResponse", targetNamespace = "http://www.sonos.com/Services/1.1", className = "smapi.ReorderContainerResponse")
    public ReorderContainerResult reorderContainer(
        @WebParam(name = "id", targetNamespace = "http://www.sonos.com/Services/1.1")
        String id,
        @WebParam(name = "from", targetNamespace = "http://www.sonos.com/Services/1.1")
        String from,
        @WebParam(name = "to", targetNamespace = "http://www.sonos.com/Services/1.1")
        int to,
        @WebParam(name = "updateId", targetNamespace = "http://www.sonos.com/Services/1.1")
        String updateId,
        @WebParam(name = "credentials", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "credentials")
        Credentials credentials,
        @WebParam(name = "context", targetNamespace = "http://www.sonos.com/Services/1.1", header = true, partName = "context")
        Context context)
        throws CustomFault
    ;

}
