
package smapi;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Sonos", targetNamespace = "http://www.sonos.com/Services/1.1", wsdlLocation = "Sonos.wsdl")
public class Sonos
    extends Service
{

    private final static URL SONOS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(smapi.Sonos.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = smapi.Sonos.class.getResource(".");
            url = new URL(baseUrl, "Sonos.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'Sonos.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SONOS_WSDL_LOCATION = url;
    }

    public Sonos(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Sonos() {
        super(SONOS_WSDL_LOCATION, new QName("http://www.sonos.com/Services/1.1", "Sonos"));
    }

    /**
     * 
     * @return
     *     returns SonosSoap
     */
    @WebEndpoint(name = "SonosSoap")
    public SonosSoap getSonosSoap() {
        return super.getPort(new QName("http://www.sonos.com/Services/1.1", "SonosSoap"), SonosSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SonosSoap
     */
    @WebEndpoint(name = "SonosSoap")
    public SonosSoap getSonosSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.sonos.com/Services/1.1", "SonosSoap"), SonosSoap.class, features);
    }

}
